"use client";
import { useEffect, useMemo, useState } from "react";

type VehicleType = "diesel" | "electric" | "hybrid" | "petrol";
type Costs = Record<"annualLicence"|"annualMaintenance"|"annualOther"|"annualTyres"|"efficiency"|"energyPrice"|"insurance"|"kilometres"|"loan"|"parking"|"tolls", number>;
type Car = { make:string; model:string; year:number; fuel:string; engineCc:number|null; ratedPowerKw:number|null; bodyType:string|null; registrations:number };
const labels={petrol:{en:"Petrol",zh:"汽油車"},hybrid:{en:"Hybrid",zh:"油電／混能車"},diesel:{en:"Diesel",zh:"柴油車"},electric:{en:"Electric",zh:"電動車"}};
const base:Costs={annualLicence:5074,annualMaintenance:9000,annualOther:2400,annualTyres:3000,efficiency:8.5,energyPrice:17.5,insurance:650,kilometres:900,loan:0,parking:3200,tolls:650};
function fee(type:VehicleType,cc=1500,power=0){if(type==="electric")return power<=75?1614:power<=125?2114:power<=175?2614:power<=225?3114:5114;const f=type==="diesel"?[6972,9396,11827,14258,16592]:[5074,7498,9929,12360,14694];return f[cc<=1500?0:cc<=2500?1:cc<=3500?2:cc<=4500?3:4]}
function defaults(type:VehicleType):Costs {if(type==="electric")return {...base,annualLicence:0,annualMaintenance:4800,efficiency:16.5,energyPrice:2.2};if(type==="hybrid")return {...base,annualMaintenance:8000,efficiency:5.2};if(type==="diesel")return {...base,annualLicence:6972,efficiency:7};return {...base}}

export default function Calculator({locale}:{locale:"en"|"zh"}){
 const en=locale==="en"; const [type,setType]=useState<VehicleType>("petrol"),[costs,setCosts]=useState<Costs>(base),[make,setMake]=useState(""),[model,setModel]=useState(""),[year,setYear]=useState(""),[selected,setSelected]=useState<Car|null>(null),[brands,setBrands]=useState<string[]>([]),[models,setModels]=useState<string[]>([]),[years,setYears]=useState<number[]>([]),[variants,setVariants]=useState<Car[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(false),[power,setPower]=useState(""),[confirmed,setConfirmed]=useState(false);
 useEffect(()=>{const c=new AbortController();void(async()=>{setLoading(true);setError(false);try{const p=new URLSearchParams({type});if(make)p.set("make",make);if(model)p.set("model",model);if(year)p.set("year",year);const r=await fetch(`/api/vehicle-models?${p.toString()}`,{signal:c.signal});if(!r.ok)throw Error();const d=await r.json() as {brands:string[];models:string[];years:number[];variants:Car[]};setBrands(d.brands);setModels(d.models);setYears(d.years);setVariants(d.variants)}catch(e){if(!(e instanceof DOMException&&e.name==="AbortError"))setError(true)}finally{if(!c.signal.aborted)setLoading(false)}})();return()=>c.abort()},[make,model,type,year]);
 const change=(next:VehicleType)=>{setType(next);setCosts(defaults(next));setMake("");setModel("");setYear("");setSelected(null);setBrands([]);setModels([]);setYears([]);setVariants([]);setPower("");setConfirmed(false)};
 const choose=(car:Car)=>{setSelected(car);if(type==="electric"){setPower(car.ratedPowerKw?.toString()??"");setConfirmed(false);setCosts(x=>({...x,annualLicence:0}))}else setCosts(x=>({...x,annualLicence:fee(type,car.engineCc??1500)}))};
 const confirm=()=>{const kw=Number(power);if(kw>0){setCosts(x=>({...x,annualLicence:fee("electric",1500,kw)}));setConfirmed(true)}};
 const total=useMemo(()=>{const energy=costs.kilometres*costs.efficiency*costs.energyPrice/100,licence=costs.annualLicence/12,maintenance=costs.annualMaintenance/12,tyres=costs.annualTyres/12,other=costs.annualOther/12,fixed=licence+maintenance+tyres+other,monthly=energy+fixed+costs.insurance+costs.parking+costs.tolls+costs.loan;return{monthly,annual:monthly*12,parts:[[en?"Fuel / charging":"燃油／充電",energy],[en?"Insurance":"保險",costs.insurance],[en?"Parking":"停車",costs.parking],[en?"Loan payment":"車貸供款",costs.loan],[en?"Tolls & road costs":"路費及隧道費",costs.tolls],[en?"Vehicle licence (monthly average)":"牌費（月均）",licence],[en?"Maintenance (monthly average)":"維修保養（月均）",maintenance],[en?"Tyres (monthly average)":"輪胎預算（月均）",tyres],[en?"Other annual costs (monthly average)":"其他年度費用（月均）",other]] as [string,number][]}},[costs,en]);
 const money=(n:number)=>new Intl.NumberFormat("zh-HK",{style:"currency",currency:"HKD",maximumFractionDigits:0}).format(n);
 const fields:[keyof Costs,string,string][]= [["kilometres",en?"Distance per month":"每月行駛里程","km"],["efficiency",en?"Energy consumption":"平均能耗",type==="electric"?"kWh/100 km":"L/100 km"],["energyPrice",type==="electric"?(en?"Electricity price":"每度電費"):(en?"Fuel price":"每公升油價"),`HKD/${type==="electric"?"kWh":"L"}`],["insurance",en?"Insurance per month":"每月汽車保險","HKD"],["parking",en?"Parking per month":"每月停車費","HKD"],["tolls",en?"Tolls per month":"每月路費及隧道費","HKD"],["loan",en?"Car loan per month":"每月車貸供款","HKD"],["annualLicence",en?"Annual vehicle licence":"每年牌費（連徵款）","HKD"],["annualMaintenance",en?"Maintenance per year":"每年維修保養","HKD"],["annualTyres",en?"Tyres per year":"每年輪胎預算","HKD"],["annualOther",en?"Other costs per year":"每年其他費用","HKD"]];
 return <div>
  <fieldset className="rounded-2xl bg-[#effaf8] p-4 sm:p-6"><legend className="px-1 text-sm font-semibold">{en?"1. Select vehicle type":"1. 選擇車輛類型"}</legend><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{(Object.keys(labels) as VehicleType[]).map(x=><button key={x} type="button" aria-pressed={type===x} onClick={()=>change(x)} className={`rounded-xl px-3 py-3 text-sm font-semibold ${type===x?"bg-[#16877e] text-white":"bg-white text-gray-700"}`}>{labels[x][locale]}</button>)}</div></fieldset>
  <section className="mt-5 rounded-2xl border border-[#bde5e1] p-4 sm:p-6"><h2 className="text-sm font-semibold">{en?"2. Select an official HK vehicle record":"2. 選擇香港運輸署車型資料"}</h2>
   <div className="mt-4 grid gap-4 sm:grid-cols-2">
    <label><span className="mb-2 block text-sm font-semibold">{en?"Brand":"品牌"}</span><select value={make} onChange={e=>{setMake(e.target.value);setModel("");setYear("");setSelected(null);setModels([]);setYears([]);setVariants([])}} className="w-full rounded-xl border bg-white p-3"><option value="">{loading&&!brands.length?(en?"Loading…":"載入中…"):(en?"Select brand":"選擇品牌")}</option>{brands.map(x=><option key={x}>{x}</option>)}</select></label>
    <label><span className="mb-2 block text-sm font-semibold">{en?"Model":"車型"}</span><select value={model} disabled={!make} onChange={e=>{setModel(e.target.value);setYear("");setSelected(null);setYears([]);setVariants([])}} className="w-full rounded-xl border bg-white p-3 disabled:bg-gray-100"><option value="">{loading&&make&&!models.length?(en?"Loading…":"載入中…"):(en?"Select model":"選擇車型")}</option>{models.map(x=><option key={x}>{x}</option>)}</select></label>
    <label><span className="mb-2 block text-sm font-semibold">{en?"Year":"年份"}</span><select value={year} disabled={!model} onChange={e=>{setYear(e.target.value);setSelected(null);setVariants([])}} className="w-full rounded-xl border bg-white p-3 disabled:bg-gray-100"><option value="">{loading&&model&&!years.length?(en?"Loading…":"載入中…"):(en?"Select year":"選擇年份")}</option>{years.map(x=><option key={x}>{x}</option>)}</select></label>
    <label><span className="mb-2 block text-sm font-semibold">{type==="electric"?(en?"Rated power (CSV reference)":"額定功率（CSV 參考）"):(en?"Engine capacity":"汽缸容量（CC）")}</span><select value={selected?`${selected.engineCc??""}|${selected.ratedPowerKw??""}`:""} disabled={!year} onChange={e=>{const car=variants.find(x=>`${x.engineCc??""}|${x.ratedPowerKw??""}`===e.target.value);if(car)choose(car)}} className="w-full rounded-xl border bg-white p-3 disabled:bg-gray-100"><option value="">{type==="electric"?(en?"Select rated power":"選擇額定功率"):(en?"Select engine capacity":"選擇汽缸容量")}</option>{variants.map(x=><option key={`${x.engineCc}-${x.ratedPowerKw}`} value={`${x.engineCc??""}|${x.ratedPowerKw??""}`}>{type==="electric"?`${x.ratedPowerKw??"—"} kW`:`${x.engineCc??"—"} cc`}</option>)}</select></label>
   </div>
   {error&&<p className="mt-3 text-sm text-red-700">{en?"Vehicle data is temporarily unavailable.":"車型資料暫時未能使用。"}</p>}
   {selected&&<div className="mt-4 rounded-xl bg-gray-950 p-4 text-white"><p className="text-xs font-semibold text-[#7ee0d6]">{en?"OFFICIAL RECORD SELECTED":"已選取運輸署資料"}</p><p className="mt-1 font-semibold">{selected.year} {selected.make} {selected.model}</p>{type!=="electric"&&<p className="mt-2 text-sm text-gray-300">{selected.engineCc??"—"} cc · {en?"annual licence":"每年牌費"} {money(costs.annualLicence)}</p>}</div>}
   {selected&&type==="electric"&&<div className="mt-3 rounded-xl border-2 border-amber-300 bg-amber-50 p-4"><h3 className="font-semibold text-amber-950">{en?"Confirm rated power from the registration document":"請按牌簿確認額定功率"}</h3><p className="mt-1 text-sm text-amber-900">{en?`CSV reference: ${selected.ratedPowerKw??"unavailable"} kW. Check the registration document and confirm.`:`運輸署 CSV 參考值：${selected.ratedPowerKw??"未提供"} kW。請核對車輛登記文件後確認。`}</p><div className="mt-3 flex gap-2"><label className="flex flex-1 rounded-lg border bg-white"><input aria-label={en?"Rated power":"額定功率"} type="number" min="0.1" step="0.1" value={power} onChange={e=>{setPower(e.target.value);setConfirmed(false);setCosts(x=>({...x,annualLicence:0}))}} className="min-w-0 flex-1 px-3"/><span className="p-2">kW</span></label><button type="button" disabled={Number(power)<=0} onClick={confirm} className="rounded-lg bg-amber-900 px-4 py-2 font-semibold text-white disabled:opacity-40">{confirmed?(en?"Confirmed":"已確認"):(en?"Confirm & calculate":"確認並計算")}</button></div>{confirmed&&<p className="mt-2 text-sm font-semibold text-emerald-800">✓ {en?"Annual licence fee":"每年牌費"}: {money(costs.annualLicence)}</p>}</div>}
   <p className="mt-3 text-xs leading-5 text-gray-500">{en?"Source: Transport Department first-registered vehicle open data (through July 2026). Petrol records also cover petrol-electric hybrids; search fills specifications and licence fee only.":"資料來源：香港運輸署首次登記車輛開放數據（截至 2026 年 7 月）。汽油資料亦包括汽油電力混合車；搜尋只會帶入車輛規格及牌費。"}</p>
  </section>
  <div className="mt-7 grid gap-5 sm:grid-cols-2">{fields.map(([key,label,suffix])=><label key={key}><span className="mb-2 block text-sm font-semibold">{label}</span><span className="flex overflow-hidden rounded-xl border"><input type="number" min="0" step="any" value={costs[key]} onChange={e=>setCosts(x=>({...x,[key]:Math.max(0,+e.target.value||0)}))} className="min-w-0 flex-1 px-4 py-3"/><span className="bg-gray-50 px-3 py-3 text-xs text-gray-500">{suffix}</span></span></label>)}</div>
  <section className="mt-8 rounded-2xl bg-gray-950 p-5 text-white sm:p-7"><p className="text-sm font-semibold text-[#7ee0d6]">{en?"Estimated ownership cost":"估算養車費用"}</p><div className="mt-3 flex justify-between"><div><strong className="block text-4xl font-bold">{money(total.monthly)}</strong><span className="text-sm text-gray-300">{en?"per month":"每月"}</span></div><p className="text-lg font-semibold">{money(total.annual)} {en?"per year":"／年"}</p></div><div className="mt-7 space-y-4">{total.parts.map(([name,value])=><div key={name}><div className="flex justify-between text-sm"><span className="text-gray-300">{name}</span><b>{money(value)}</b></div><div className="mt-1 h-2 rounded bg-white/10"><div className="h-full rounded bg-[#47cabc]" style={{width:`${Math.min(100,total.monthly?Math.max(1,value/total.monthly*100):0)}%`}}/></div></div>)}</div></section>
  <div className="mt-5 flex justify-between rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><p>{en?"Government records and preset costs are references. Confirm against the registration document and quotations.":"政府登記資料及預設開支只供試算，請按牌簿及實際報價核對。"}</p><button type="button" onClick={()=>change(type)} className="font-semibold underline">{en?"Reset":"重設"}</button></div>
 </div>
}
